name: Deploy .NET no Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Trilha-Esporte

    steps:
      # ðŸ”¹ Checkout do cÃ³digo
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v4

      # ðŸ”¹ Autenticar no Google Cloud
      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ðŸ”¹ Configurar Docker para Artifact Registry
      - name: Configurar Docker para Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # ðŸ”¹ Configurar QEMU para multi-arch
      - name: Configurar QEMU para multi-arch
        uses: docker/setup-qemu-action@v3

      # ðŸ”¹ Configurar Buildx
      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      # ðŸ”¹ Definir nome da imagem Docker com nome padrÃ£o
      - name: Definir nome da imagem
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dotnet-repo/trilha-esporte:v1.0-${{ github.sha }}"
          echo "IMAGE_NAME<<EOF" >> $GITHUB_ENV
          echo "$IMAGE_NAME" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # ðŸ”¹ Construir a imagem Docker com Buildx
      - name: Construir a imagem Docker com Buildx
        run: |
          echo "Construindo a imagem Docker..."
          docker buildx build \
            --tag ${{ env.IMAGE_NAME }} \
            --file Dockerfile \
            --progress plain \
            --push \
            .

      # ðŸ”¹ Enviar a imagem para Artifact Registry
      - name: Enviar a imagem para Artifact Registry
        run: |
          echo "Enviando imagem para Artifact Registry..."
          docker push ${{ env.IMAGE_NAME }}

      # ï¿½ Chave SSH
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # ðŸ”¹ Realizar o deploy no Cloud Run
      - name: Deploy no Cloud Run
        run: |
          echo "Realizando deploy no Cloud Run..."
          gcloud run deploy trilha-esporte \
            --image=${{ env.IMAGE_NAME }} \
            --region=us-central1 \
            --platform=managed \
            --port=8080 \
            --allow-unauthenticated \
            --timeout=2000s \
            --set-env-vars="DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }}"

      # ðŸ”¹ Exibir URL do serviÃ§o
      - name: Exibir URL do serviÃ§o
        run: |
          echo "URL do serviÃ§o:"
          gcloud run services describe trilha-esporte --region=us-central1 --format 'value(status.url)'
